inmotionhosting/ansible-role-wordpress

defaults/main.yml
templates/etc/httpd/conf.d/site.conf.j2
templates/etc/php-fpm.d/site.conf.j2

Configure FPM Status and Ping pages in individual site pool settings. Additionally each Apache virtualhost has a Location block to handle the proxypass to fcgi. Switched FPM process manager from ondemand to dynamic with settings for min_spare_servers, max_spare_servers, and start_servers that is 1/3 of the max_children calculated from memory resources.

Configure FPM Status page and dynamic pm

---

tasks/wordpress.yml

- Don't send an email notification to the new admin user.

NGX-241: skip welcome email when installing wp core

---

tasks/Debian.yml

- worker MPM -> event MPM
- also replace instances of "apache2_module" with "community.general.apache2_module" (FQDN).  This prevents failures in name resolution which have been occurring. (see: NGX-261)

NGX-277: worker MPM -> event MPM

---

README.md
meta/main.yml
molecule/default/converge.yml
requirements.yml

- wp3-ultrastack-playbook is configured to run apache/mysql/php-fpm roles prior to the wordpress role.  Having wordpress configured with these as dependencies causes duplicate runs of them.

NGX-287: remove all dependencies on apache/mysql/php-fpm

---

tasks/main.yml
templates/etc/httpd/conf.d/site.conf.j2

- Remove any extra site configs for a different site_domain used in a previous playbook run.

NGX-289: remove extra apache site configs

---

tasks/main.yml
templates/etc/php-fpm.d/site.conf.j2

- Remove extra PHP-FPM pool configs that were created for different site_domain's in previous ansible runs.

NGX-289: remove extra php-fpm pool configs

---

templates/etc/httpd/conf.d/site.conf.j2

When use_letsencrypt=false is passed an extra variable to the ansible-playbook command, it is treated as a string. If a python string is non-empty then it will always evalute to true. Instead we need to cast use_letsencrypt to a bool. This ensures the logic works as intended in several places within the role.

NGX-299: cast use_letsencrypt to bool

---

tasks/main.yml
templates/etc/httpd/conf.d/site.conf.j2

- Logic to set the appropriate protocol (http/https) in the siteurl was not working properly.  If use_letsencrypt=false is passed as an extra variable, it is treated as a string and evaluates to true unless casted to a bool.

NGX-300: cast usage of use_letsencrypt in main.yml to bool

---

README.md
defaults/main.yml
tasks/main.yml
tasks/wordpress.yml

This feature/variable allows the entire server to be configured (all components of the stack), but will not install WordPress.  This allows for a server to be stood up in a "pre-warmed" state, but without having an install of WordPress open to the public that is not being used.

NGX-316: install_wordpress boolean; server setup w/out wordpres

---

defaults/main.yml
tasks/main.yml
templates/etc/httpd/conf.d/site.conf.j2
templates/etc/php-fpm.d/site.conf.j2

- Resolve error logging failures; Configure error logging to path which `system_user` can write to.
- Port additional settings from existing Ultrastack configuration to fpm pool configuration: chdir, catch_workers_output, doc_root, pool name scheme, security.limit_extensions.
- Add request_slowlog_timeout variable for the ability to log slow fpm executions. A value of '0' means 'Off'. Available units: s(econds)(default), m(inutes), h(ours), or d(ays). Default value: 0.
- Various ansible linting fixes

NGX-344: fix fpm pool logging; port addtl php settings; linting

---

templates/etc/httpd/conf.d/site.conf.j2

- Wrapping RemoteIP* directives in an <IfModule> block prevents Apache from failing to start if the Remote IP module is not loaded.

NGX-368: Use <IfModule> around RemoteIP* directives

---

tasks/main.yml

- Certain circumstances cause the playbook to apply changes without restarting the service.  Subsequent runs do not apply any changes, so the service is again not restarted.  This can cause service to be stuck in running state with outdated configs which playbook can not correct.  For this reason, we notify the apache, php-fpm, and nginx restart handlers on every run.

NGX-380: Always trigger apache/php-fpm restart handlers

---

defaults/main.yml
templates/etc/php-fpm.d/site.conf.j2

- The number of workers is being scaled more conservatively with this change.  Instead of expecting an fpm work to use 64 MB, we now allocate 192 MB.  This is based off observations from real time data.  It also takes into account that the default memory_limit is 512 MB for php in /etc/php.ini

NGX-725: update php fpm pool worker counts

---

defaults/main.yml
tasks/main.yml

- Changing the site's url creates new nginx and apache config files for the new domain.  We've been removing everything except the newest one.  This new feature allows us the user to exclude removal of any site configs that match the provided patterns.  This way we can persist the configs for the server hostname itself.

NGX-733: do not remove site configs that match given patterns

---

molecule/default/converge.yml
tasks/main.yml

Guid's are usually the URL, and if changing domain names, you want to switch it. Only preserve it if you are staying on the same domain, rss readers use it for ensuring the feed is correct, among other things.

NGX-730: No --skip-columns=guid

---

meta/main.yml
requirements.yml
tasks/main.yml

This adds the redis group to system_user allowing WordPress plugins to connect to the redis unixsocket.

NGX-757: Redis unixsocket support

---

defaults/main.yml
tasks/main.yml
templates/etc/nginx/conf.d/site.conf.j2
templates/etc/nginx/conf.d/upstream.conf.j2

Following execution of wp search-replace, wp-cli prompts the user to flush cache via 'wp cache flush'.  Failure to do so will cause subsequent wp-cli command to result in Error such as setting the home, or siteurl wp_option options.
Also restored selinux functionality.  This had previously been removed in https://github.com/inmotionhosting/ansible-role-wordpress/commit/db90bd55f238b50dc1d108feea4f87c01d9590e0.
The name of the upstream server in /etc/nginx/conf.d/upstream.conf was changed from http_backend to apache.

NGX-762: flush object cache after wp search-replace

---

tasks/main.yml

We no longer load all themes and plugins when executing certain wp-cli commands that do not need them.  This commit makes a few of the tasks less susceptible to being OOM killed.

NGX-766: Skip loading all themes and plugins

---

tasks/wordpress.yml

The mysql unix socket provides performance improvement over using 3306/tcp.

NGX-771: Use unixsocket for DB_HOST

---

templates/etc/httpd/conf.d/site.conf.j2
templates/etc/nginx/conf.d/site.conf.j2
templates/etc/nginx/conf.d/upstream.conf.j2

When a user changes their Site url to something other than the VPS hostname we provide them with by default, the playbook will add additional configuration to NGiNX and Apache, so that requests to the VPS hostname still properly load the WordPress site.

NGX-733: Preserve hostname config

---

handlers/main.yml
requirements.yml
tasks/main.yml

Add additional output to playbook execution.  Failed syntax checks will result in the error being logged to playbook output.  This is useful for debugging and troubleshooting.  We also have the ability to skip execution of handlers if syntax is invalid.

NGX-761: Check service configuration syntax

---

defaults/main.yml
requirements.txt
requirements.yml
templates/etc/nginx/conf.d/site.conf.j2

Anything going to wp-json can probably be omitted from the cache.
Also download collections from GitHub instead of Galaxy until issues with New Galaxy can be resolved.

NGX-789: /wp-json* Bypasses NGiNX cache; Install collections from GitHub

---

templates/etc/nginx/conf.d/site.conf.j2

The https redirect in our nginx site configuration will cause a redirect loop when used with CloudFlare’s default settings.  It was determined that our config should not be opinionated in this decision to redirect a user.  We should rely on the WordPress site url, or .htaccess (WordPress Plugin code) to do the redirect.

NGX-795: Remove NGINX https redirect

---

tasks/main.yml

In some cases we fail to set the siteurl via wp-cli.  This can be because of a plugin, manual definition in wp-config.php, or other variable reasons.  We will now fallback on setting the siteurl in wp-config.php using WP_SITEURL and WP_HOME constants if the wp-cli method fails.

NGX-762: Siteurl fallback in wp-config.php

---

requirements.yml
tasks/main.yml

There are two actions which can be performed against a target server from the application interface.  The two actions are changing the Site URL and changin the PHP Version.  Both of these tasks do not require the playbook to be ran in its entirety.  These new tags isolate the tasks required to complete each action.  This improves speed and interaction with the server playbook.

NGX-780: Introduce siteurl, phpversion tags

---

defaults/main.yml
templates/etc/php-fpm.d/site.conf.j2

PHP disable_functions allow the user to customize their PHP configuration for security and other reasons.

NGX-811: Make PHP disable_functions variable configurable

---

templates/etc/httpd/conf.d/site.conf.j2
templates/etc/nginx/conf.d/site.conf.j2

The expected behavior when a server is configured for either www.domain.com or domain.com is that an SSL and the appropriate service configs should be present for both www.domain.com and domain.com.  This commit ensures that is the outcome.

NGX-817: Handle site_domain when starting with www.

---

tasks/main.yml

Ensure task continuity by ignoring non-critical command failures
- Add  to the WordPress cache flush task to prevent non-zero exit codes from failing the playbook execution. This change allows the playbook to continue running even if the cache flush command encounters minor, non-critical errors, ensuring that subsequent tasks are not unjustly impacted by this step's failure status.
This adjustment is made to accommodate scenarios where the wp cache flush command might return a non-zero exit code due to known, benign issues that do not affect the overall success of the operation. It improves playbook resilience and execution consistency across environments with varying cache states.

NGX-838: Ignore Object Cache flush failures

---

defaults/main.yml

- Update nginx_cache_bypass_paths regex to include /ultrastack.* pattern. This change ensures that requests to paths starting with /ultrastack are not served from cache, addressing the need for dynamic content delivery and updates related to Ultrastack services like the File Manager and Database Manager.
This modification enhances our Nginx configuration to better support the caching exceptions required for Ultrastack functionalities, ensuring that updates and dynamic content are delivered reliably and without delay.

NGX-855: Extend Nginx cache bypass to include Ultrastack paths

---

templates/etc/nginx/conf.d/site.conf.j2

- Add a line to the template to include customer user includes within /etc/nginx/user-includes.d/
- Add block comments to various location blocks in NGINX config to inform the user of each block's purpose

NGX-860: Custom NGINX Server Includes

---

templates/etc/nginx/conf.d/default.conf.j2
templates/etc/nginx/conf.d/site.conf.j2

```
Changes with nginx 1.25.1                                        13 Jun 2023
*) Feature: the "http2" directive, which enables HTTP/2 on a per-server
basis; the "http2" parameter of the "listen" directive is now
deprecated.
```

NGX-868: Remove 'listen...http2;' in favor of 'http2 on;'

---

templates/etc/httpd/conf.d/site.conf.j2

- Changed disablereuse from off to on to ensure TCP connections close after each request. This addresses PHP-FPM's single-connection handling and prevents excess backend connections from exhausting fpm workers

NGX-880: Update Apache config

---

templates/etc/nginx/conf.d/site.conf.j2

Add two additional pieces of logic into the server hostname block.
1. Requests to 'wp-json' are able to be proxied as if the request was made to the site url
2. Requests with the 'rest_route' query string are able to be proxied as if the request was made to the site url
All other requests to the server hostname will not be proxied as if they were made to the site url.  This prevents the entire WordPress site from being accessible over the server hostname.

NGX-878: Update Nginx Site Configuration

---

templates/etc/httpd/conf.d/site.conf.j2
templates/etc/nginx/conf.d/site.conf.j2

Apache:
- Also create virtualhost listening on port 8080 when use_letsencrypt is true
Nginx:
- Have separate Nginx server blocks for ports 80 and 443 when use_letsencrypt is true. This allows nginx to proxy http (nginx) requests on port 80 to the httpd (apache) virtualhost listening on port 8080 to preserve certain characteristics about the original request. This fixes issues where .htaccess redirects using the '[HTTPS](https://httpd.apache.org/docs/current/mod/mod_rewrite.html#rewritecond)' apache special Server-Variable can not detect the original protocol.

NGX-865: Update Nginx/Apache Site Config
